[project]
name = "yaki"
version = "1.0.0"
description = "Anonymous People Counter"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx2",
    "nicegui",
    "orjsonl",
    "starlette",
    "uvicorn",
    "lap",
    "shapely",
    "picamera2; sys_platform == 'linux'",
    "pillow",
    "supervision",
    "trackers"
]

[project.scripts]
yaki-server = "yaki.server:main"
yaki-dev = "yaki.server:main_dev"
yaki-camera = "yaki.camera:main"
# yaki-client-aicam = "detect_aicam:main"
# yaki-client-webcam = "detect_webcam:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13"]
build-backend = "uv_build"